name: Generate snake animation

on:
  schedule: # her 12 saatte bir çalıştır
    - cron: "* */12 * * *"

  workflow_dispatch: # elle başlatma özelliği

  push:
    branches:
    - master # sadece master branch için çalıştır

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg for 2025 commits
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark
          year: 2025 # Yalnızca 2025 yılına ait commit'ler

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Hedef branch
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

